config/routes.rb
Rails.application.routes.draw do
 
  
   root 'welcome#index'
   get '/', to: "welcome#index"
   
  get '/about', to: 'welcome#about'
  get '/index', to: 'welcome#index'
  get '/info', to: 'welcome#info'
  get '/legal', to: 'welcome#legal'
  get '/privacy', to: 'welcome#privacy'
  get '/contact', to: 'contacts#index'
  
    resources :faces do
      member do
        post 'like'
      end
      
    end
    
    resources :users, except: [:new]
    
    get '/register', to: 'users#new'
    
    resources :contacts
    
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
    

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to faces_path if logged_in?
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="center jumbotron Bcolor">
  <h1> Welcome to DrunkFaces</h1>
  
  <h2> Where you can share with your friends or the whole world how drunk you really got</h2>
  
  <%= link_to "Sign up now!", register_path, class:"btn btn-lg btn-warning" %>
</div>
<div class="row">
  <div class="col-xs-6 col-lg-6" align="center">
    <h3 class="midrow ">
      View Public Faces
    </h3>
    <h2> Browse and View drunk faces that drunks shared publicly</h2>
    <p><%= link_to "Browse DrunkFaces", faces_path, class: "btn btn-info btn-small " %></p>
  </div>
  
  
   <div class="col-xs-6 col-lg-6" align="center">
    <h3 class="midrow">
      Learn More About DrunkFaces
    </h3>
    <h2> Learn Everything you need to know about DrunkFaces</h2>
    <p><%= link_to "Learn More", "info", class: "btn btn-info btn-small" %></p>
  </div>
  


</div>

  <br> </br>
  

app/views/welcome/privacy.html.erb
<h2 class="bold">
Privacy Policy
</h2>
<p>
Your privacy on the Internet is important to us. As a part of the operation of MyDrunkFaces.com, we gather your e-mail address only when you submit it to subscribe to our newsletter. We respect your privacy and will not share or sell your e-mail address to a third party. However, we may use it to contact you regarding site updates, news, and information.
</p>
<p>
The foregoing policy is effective as of MAY 2015, and MyDrunkFaces reserves the right to change this policy at any time. Please check this page periodically for changes. This statement and policies outlined herein are not intended to and do not create any contractual or other legal rights in or on behalf of any party.
</p>
<br></br>

<h2 class="bold">
THIRD PARTY ADVERTISING
</h2>
<p>
We use various third-party advertising companies to serve ads when you visit our Web site. These companies may use information (not including your name, address, email address or telephone number) about your visits to this and other Web sites in order to provide advertisements on this site and other sites about goods and services that may be of interest to you. If you would like more information about this practice and to know your choices about not having this information used by these companies, please contact us using the contact form.
</p>
<br></br>

<h2 class="bold">
THIRD PARTY COOKIES
</h2>
<p>
In the course of serving advertisements to this site, our third-party advertiser may place or recognize a unique “cookie” on your browser.
</p>
<p>
If you have any question about this privacy, please contact us at MyDrunkFaces.com .
</p>