config/routes.rb
Rails.application.routes.draw do
 
  
   root 'welcome#index'
   get '/', to: "welcome#index"
   
  get '/about', to: 'welcome#about'
  get '/index', to: 'welcome#index'
  get '/info', to: 'welcome#info'
  get '/legal', to: 'welcome#legal'
  get '/privacy', to: 'welcome#privacy'
  get '/contact', to: 'contacts#index'
  
    resources :faces do
      member do
        post 'like'
      end
      
    end
    
    resources :users, except: [:new]
    
    get '/register', to: 'users#new'
    
    resources :contacts
    
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
    

end

app/models/face.rb
class Face < ActiveRecord::Base 
    belongs_to :user
    has_many :likes
    validates :user_id, presence:true
    validates :description, presence: true, length: { minimum: 4, maximum: 120 }
    mount_uploader :picture, PictureUploader
    validates :picture, presence:true
    validate :picture_size
    default_scope -> { order(updated_at: :desc)}
    
    def thumbs_up_total
        self.likes.where(like: true).size
    end
    
    def thumbs_down_total
        self.likes.where(like: false).size
    end

    private
        def picture_size
            if picture.size > 5.megabytes
                errors.add(:picture, "Should be less than 5MB")
            end
        end
    
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController
	
    
    def index
        @faces = Face.paginate(page: params[:page], per_page: 4).order("updated_at DESC")
    end
    
    def show
    @face = Face.find(params[:id])
    end
    
    def new
    @face = Face.new
    end
    
    def create

		@face = Face.new(face_params)
		@face.user = current_user

		if @face.save
			flash[:success] = "Your face was submitted successfully!"
			redirect_to faces_path

		else
			render :new
		end
    end
    
    def edit
        @face = Face.find(params[:id])
    end
    
    def update
        @face = Face.find(params[:id]) 

		if @face.update(face_params)
			flash[:success] = "Your face was updated successfully!"
			redirect_to faces_path(@face)
        else
			render :edit
		end
    end
	
	def like 
	    
	    @face = Face.find(params[:id])
	    like = Like.create(like: params[:like], user: User.first, face: @face)
	    if like.valid?
	    flash[:success] = "Your selection was posted!"
	    redirect_to :back
	    else
	    flash[:danger] = "You can only like/dislike a face once!"
	    redirect_to :back
	    end
	end
	
	private
	    def face_params
	    	params.require(:face).permit(:picture, :description)
	    end
end

app/views/faces/_form.html.erb
<%= render 'shared/errors', obj: @face %>

<div class="row">
    <div class="well col-xs-6 col-lg-6 col-lg-offset-3 col-xs-offset-3 center">
        
        <%= form_for(@face, html: { multipart: true }) do |f| %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        <h5> Describe the Photo: </h5>
        <%= f.text_area :description, rows:3 %>
        
        <%= f.submit(@face.new_record? ? 'Submit Photo' : 'Edit Photo' , class: "btn btn-success  btn-small" )%>
        <% end %>
    </div>
</div>

<script type='text/javascript'>
    
    $('#face_picture').bind('change', function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }    
    });
    
</script>

app/views/faces/edit.html.erb
<%= render 'shared/page_title', title: "Edit a Face" %>
<%= render 'form' %>

app/views/faces/index.html.erb
<%= render 'shared/page_title', title: "All faces" %>

<%= will_paginate %>


<% @faces.each do |face| %>
    <div class="row">
        <div class="col-lg-2 col-xs-2">
            <section class="user_info center">
                <%= link_to gravatar_for(face.user, size:100), user_path(face.user) %>
            <h5><%= face.user.firstname %> <%= face.user.lastname %></h5>
            </section>
        </div>
        <div class="col-lg-8 col-xs-8 well">
            <h4><%= link_to (image_tag(face.picture.url, size:"250x150", class:"gravatar")), face_path(face) %> </h4>
            <p> <%= face.description %></p>
            
            <p>
                <span class= 'quiet'> <small>Created <%= time_ago_in_words(face.created_at) %> ago, </small> </span>
                <span class= 'quiet'> <small>Updated <%= time_ago_in_words(face.updated_at) %> ago</small> </span>
            </p>
            <div class="pull-right">
                <%= link_to like_face_path(face, like: true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up">&nbsp</i><%= face.thumbs_up_total %> &nbsp&nbsp
                <% end %> 
                <%= link_to like_face_path(face, like: false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down">&nbsp</i> <%= face.thumbs_down_total %>
                <% end %>
            </div>
        </div>
    </div>
    <hr/>
<% end %>

<%= will_paginate %>

app/views/faces/new.html.erb
<%= render 'shared/page_title', title: "Add a Face" %>

<%= render 'form' %>

app/views/faces/show.html.erb
<%= render 'shared/showpage_title', title: @face.user.firstname %> 

<div class="row">
    <div class="col-lg-3 col-xs-3 ">
        <%= link_to gravatar_for(@face.user, size: 150), user_path(@face.user) %>
        <p>
            <h5><%= @face.user.firstname %> <%= @face.user.lastname %></h5>
            <h5><%= @face.user.college if @face.user.college? %></h5>
            <h5>State: <%= @face.user.state if @face.user.state? %></h5>
            <h5>Member since: <%= time_ago_in_words(@face.user.created_at) %> ago</h5>
        </p>
    </div>
    <div class="col-lg-9 col-xs-9">

        <div class="show_face">
            <%= image_tag(@face.picture.url, size:"640x480", class:"gravatar") if @face.picture? %>
        </div>
        <h3> <% @face.description %> </h3>
        <div class="well col-lg-9 col-xs-12">
            <p>
                <strong> Description:</strong>
            </p>
            <%= simple_format(@face.description) %>
            <div class="pull-right">
                <%= link_to like_face_path(@face, like: true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up">&nbsp</i><%= @face.thumbs_up_total %> &nbsp&nbsp
                <% end %> 
                <%= link_to like_face_path(@face, like: false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down">&nbsp</i> <%= @face.thumbs_down_total %>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="col-lg-10 col-xs-12 ">
    <h5> <%= link_to "Return to Faces", faces_path, class: "btn btn-success  btn-small nav_item pull-right" %> </h5>
    <% if logged_in? and @face.user == current_user %>
        <h5> <%= link_to "Edit this Photo", edit_face_path(@face), class: "btn btn-success nav_item pull-right" %> </h5>
    <% end %>
</div>