config/routes.rb
Rails.application.routes.draw do
 
  
   root 'welcome#index'
   get '/', to: "welcome#index"
   
  get '/about', to: 'welcome#about'
  get '/index', to: 'welcome#index'
  get '/info', to: 'welcome#info'
  get '/legal', to: 'welcome#legal'
  get '/privacy', to: 'welcome#privacy'
  get '/contact', to: 'contacts#index'
  
    resources :faces do
      member do
        post 'like'
      end
      
    end
    
    resources :users, except: [:new]
    
    get '/register', to: 'users#new'
    
    resources :contacts
    
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
    

end

app/views/layouts/_footer.html.erb
<br></br>

<div class="footer">
        
    <p>&copy;2015 DrunkFaces.  All rights reserved.</p>
        
        <div class="foot-bar">
            <p>     
                <%= link_to "About", about_path, class: "btn btn-inverse btn-small " %>  
                <%= link_to "Legal", legal_path, class: "btn btn-inverse btn-small " %>
                <%= link_to "Privacy", privacy_path, class: "btn btn-inverse btn-small " %>
                <%= link_to "Contact Us", contacts_path, class: "btn btn-inverse btn-small " %>
            </p>

        </div>
        
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>">
			<%= message %>
			<a class="close" data-dismiss="alert">&#215;</a>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<header class ="navbar navbar-fixed-top navbar-default">
   <div class="container">
          
           <%= link_to "DrunkFaces", root_path, class:"btn btn-lg btn-success", id: "logo" %>
           
           <% if logged_in? %>
            <div class="nav_item">
            <%= link_to "Post New Face", new_face_path, class:"btn btn-default btn-primary" %>
            </div>
            <% end %>
            
            
           <% if logged_in? %>
             <ul style="list-style-type: none;" class="nav_item1">
				           <li class="dropdown">
					            <%= link_to "#", class: "btn btn-success border-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
					            <%= current_user.firstname %> <b class="caret"></b>
					            <% end %>
					           <ul class="dropdown-menu">
						           <li><%= link_to "View Profile", user_path(current_user) %></li>
						           <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
						           <li class="divider"></li>
						           <li><%= link_to "Logout", logout_path %></li>
					           </ul>
				           </li>
			          </ul>
			          
			          <% else %>
			            <div class="nav_item1">
                <%= link_to "Sign In", login_path, class:"btn btn-default btn-primary" %>
               </div>
            <% end %>
            
   </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyDrunkFaces</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="col-xs-12 col-lg-12">
  
  <%= render 'layouts/navigation' %>
  
  <div class="container">
    <%= render 'layouts/messages'  %>
    <%= yield %>
   
  </div>
  
  <div class ="container">   
  <%= render 'layouts/footer' %>
  </div>   
</body>
</html>